### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by priamm** [krossovochkin/KWeather#1]
java.lang.OutOfMemoryError: Failed to allocate a 66529400 byte allocation with 25165824 free bytes and 61MB until OOM, target footprint 162387864, growth limit 201326592
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
        at java.lang.StringBuffer.toString(StringBuffer.java:671)
        at java.io.StringWriter.toString(StringWriter.java:210)
        at kotlin.io.TextStreamsKt.readText(ReadWrite.kt:108)
        at com.krossovochkin.kweather.shared.common.storage.citylist.FileCityListDatasource.getCityListInternal(FileCityListDatasource.kt:33)
        at com.krossovochkin.kweather.shared.common.storage.citylist.FileCityListDatasource.access$getCityListInternal(FileCityListDatasource.kt:11)
        at com.krossovochkin.kweather.shared.common.storage.citylist.FileCityListDatasource$getCityList$2.invokeSuspend(FileCityListDatasource.kt:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(

**Comment by krossovochkin** [comment]
Hi @priamm, thanks for posting

**Comment by krossovochkin** [comment]
Fixed by improving setup: instead of loading everything into memory (JSON string, list of parsed objects) - parse on the fly from the `InputStream`.
Setup step now might take longer (need to wait for all the data processed) but there should be no crash.

Thanks for posting!
